version: '1.0'

general:
    name: Irrigation
    id: irrigation1   # no spaces

scheduler:
    - '21:00'
    - '05:00'

zones:
    backyard-front:
        type: sprinklers
        mode: Auto
        waterRequirement: 10
        valveMqtt: { commandTopic: 'abc/def', commandOn: 'ON', commandOff: 'OFF' }

    garden:
        type: sprinklers
        mode: Auto
        waterRequirement: 10
        valveMqtt: { commandTopic: 'abc/def', commandOn: 'ON', commandOff: 'OFF' }

    thujas:
        type: drip-line
        mode: Auto
        waterRequirement: 10
        valveMqtt: { commandTopic: 'abc/def', commandOn: 'ON', commandOff: 'OFF' }

waterSupplies:
    grid:
        capacity: 'infinite'
        flow: 20
        pressure: 6

    rainwaterTank:
        capacity: '200'
        flow: 10
        pressure: 3
        cmdTopic: 'valve/1'

sensors:
    soil-moisture-1:
        type: soil-moisture
        zones:
            - backyard front
        stateTopic: 'sensor/111/xxx'

mqtt:
    host: 127.0.0.1
#    host: 192.168.1.11
    port: 1883
#    username: domoticz
#    password: xxx
#    discoveryTopicPrefix: homeassistant
